# Generated by Django 3.2.9 on 2023-06-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.states')),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('near_railway_station', models.CharField(blank=True, max_length=100, null=True)),
                ('main_railwy_station', models.CharField(blank=True, max_length=100, null=True)),
                ('near_aiport', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.states')),
            ],
        ),
    ]
